# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=120)),
                ('courseDescription', models.TextField()),
                ('courseCost', models.CharField(max_length=120)),
                ('courseCategory', models.CharField(max_length=120)),
                ('CourseModeOfDelivery', models.CharField(max_length=120)),
                ('CourseSkillLevel', models.CharField(max_length=120)),
                ('CoursePrerequisite', models.CharField(max_length=120)),
                ('updated', models.DateField(auto_now=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
